spring.application.name=EcommerceAPI
#dataSource
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
#hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#Tomcat Server
server.port=8185
#RazorPay
razorpay.key_id=rzp_test_qDAV8sCeGjU7AR
razorpay.key_secret=5xUjsPKLhJdGWA0wp2fbgP9c
#password
#spring.security.user.password=Test12345

jwt.secret=c9fb8b1954a614d815b10d6ebaa93172ffe75c7c468f78f379c8626e20850b94
## 1h in millisecond
jwt.expiration-ms=3600000